services:
  postgres:
    image: postgres:18
    container_name: nestjs-template-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs-template
    volumes:
      - data_postgres:/var/lib/postgresql

  redis:
    image: redis:7
    container_name: nestjs-template-redis
    ports:
      - '6379:6379'
    volumes:
      - data_redis:/data

volumes:
  data_postgres:
  data_redis:
